sudo: required

services:
  - docker

before_install:
 - sudo docker pull centos:7

script:
 - sudo docker run --rm=true -v `pwd`:/git centos:7 /bin/bash -c "yum install -y make gcc rpm-build libnl3-devel && cd /git && chown -R root:root . && ./buildrpm.sh"
